### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mnot** [hannesg/uri_template#1]
Hi,

FYI, we've started collection JSON-formatted tests for URI templates here:
  https://github.com/uri-templates/uritemplate-test
starting with the examples from the spec.

If you'd like to use them in your project, please feel free, and of course we'd love a pull request if you have additional tests in the same format.

(Sorry to submit this as an issue, but I didn't see any other way to contact you.)

Cheers,

**Comment by hannesg** [comment]
Hi,

sorry, forgot to add a public email on my profile. Now it's there.

I would really like to add different draft-versions for the test suite. I want to implement version-8 alongside version-7. Then one could have a simple tool which will read the json and test both versions.

**Comment by 0610919566** [comment]
hannesg merged commit 17c4182 into master over 3 years ago
