### ISSUE TITLE
Partial expand changed behavior

### ISSUE THREAD

**Issue by plexus** [hannesg/uri_template#13]
Hi, I notice the behavior of URITemplate has changed between 0.6.0 and 0.7.0

``` ruby
URITemplate.new('/foo/{x}/{y}').expand_partial(x: 123).to_s
#0.6.0 => "/foo/123/{y}"
#0.7.0 => "/foo/123{x}/{y}"
```

is there an API to get the old behaviour? I'm using URITemplate for [Yaks](https://github.com/plexus/yaks) and this is blocking me from upgrading.

**Comment by etehtsea** [comment]
+1. No idea what to do with it now.
